# @package _global_
inference:
  name: null
  gpu_id: 0  # CUDA GPU to use
  seed: 123


  # Directory of software, weights, and outputs.
  pt_hub_dir: ${hydra:runtime.cwd}/src/torch/
  output_dir: ./foldflow_outputs

  # Path to model weights.
  weights_path: ${hydra:runtime.cwd}/src/foldflow/last.ckpt

  flow:
    # Number of steps.
    num_t: 500
    # Analogous to sampling temperature.
    noise_scale: 0.1
    # Final t.
    min_t: 0.01

  samples:
    # Number of backbone samples per sequence length.
    samples_per_length: 5
    # Number of ESMFdold samples per backbone sample.
    seq_per_sample: 5
    # Minimum sequence length to sample.
    min_length: 100
    # Maximum sequence length to sample.
    max_length: 110
    # gap between lengths to sample. i.e. this script will sample all lengths
    # in range(min_length, max_length, length_step)
    length_step: 50