inference:

  task_type: scaffold # scaffold

  unconditional:
    weights_path: ${hydra:runtime.cwd}/src/genie2/last.ckpt
    output_dir: ./genie2_outputs/
    num_samples: 5 # number of samples per length
    batch_size: 4 # number of samples with once inference
    scale: 0.6 # Sampling noise scale
    max_length: 60
    min_length: 50
    length_step: 1

  scaffold:
    weights_path: ${hydra:runtime.cwd}/src/genie2/last.ckpt
    output_dir: ./genie2_outputs/
    num_samples: 4 # number of samples per task
    batch_size: 4 # number of samples with once inference
    scale: 0.4 # Sampling noise scale
    strength: 0
    motif_name: null
    datadir: ${hydra:runtime.cwd}/src/genie2/design25